################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_GEOS_C "libgeos_c")
    if (NOT PC_GEOS_C_FOUND)
        pkg_check_modules(PC_GEOS_C "libgeos_c")
    endif (NOT PC_GEOS_C_FOUND)
    if (PC_GEOS_C_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_GEOS_C_CFLAGS} ${PC_GEOS_C_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_GEOS_C_INCLUDE_HINTS ${PC_GEOS_C_INCLUDE_DIRS} ${PC_GEOS_C_INCLUDE_DIRS}/*)
        set(PC_GEOS_C_LIBRARY_HINTS ${PC_GEOS_C_LIBRARY_DIRS} ${PC_GEOS_C_LIBRARY_DIRS}/*)
    endif(PC_GEOS_C_FOUND)
endif (NOT MSVC)

find_path (
    GEOS_C_INCLUDE_DIRS
    NAMES geos_c.h
    HINTS ${PC_GEOS_C_INCLUDE_HINTS}
)

find_library (
    GEOS_C_LIBRARIES
    NAMES geos_c
    HINTS ${PC_GEOS_C_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    GEOS_C
    REQUIRED_VARS GEOS_C_LIBRARIES GEOS_C_INCLUDE_DIRS
)
mark_as_advanced(
    GEOS_C_FOUND
    GEOS_C_LIBRARIES GEOS_C_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
