/*  =========================================================================
    geodist - class description

    Copyright (c) 2017 Inkblot Software Limited.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.
    =========================================================================
*/

#ifndef GEODIST_H_INCLUDED
#define GEODIST_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT
//  @warning Please edit the model at "api/geodist.xml" to make changes.
//  @interface
//  This API is a draft, and may change without notice.
#ifdef GEOUTILS_BUILD_DRAFT_API
//  *** Draft method, for development use, may change without warning ***
//  Returns the distance between two points in metres.
//  Calcualted using the haversine formula, so not accurate over
//  large distances.
GEOUTILS_EXPORT double
    geodist_haver (GUGeoPos pos1, GUGeoPos pos2);

//  *** Draft method, for development use, may change without warning ***
//  Self test of this class.
GEOUTILS_EXPORT void
    geodist_test (bool verbose);

#endif // GEOUTILS_BUILD_DRAFT_API
//  @end

#ifdef __cplusplus
}
#endif

#endif
