/*  =========================================================================
    geopip - class description

    Copyright (c) 2017 Inkblot Software Limited.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.
    =========================================================================
*/

#ifndef GEOPIP_H_INCLUDED
#define GEOPIP_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT
//  @warning Please edit the model at "api/geopip.xml" to make changes.
//  @interface
//  This API is a draft, and may change without notice.
#ifdef GEOUTILS_BUILD_DRAFT_API
//  *** Draft method, for development use, may change without warning ***
//  Construct from a Well Known Text text string
GEOUTILS_EXPORT geopip_t *
    geopip_new_wkt (const char *wkt_str);

//  *** Draft method, for development use, may change without warning ***
//  Destroy the geopip.
GEOUTILS_EXPORT void
    geopip_destroy (geopip_t **self_p);

//  *** Draft method, for development use, may change without warning ***
//  Does the polygon contain the provided point?
GEOUTILS_EXPORT bool
    geopip_contains (geopip_t *self, GUGeoPos geopos);

//  *** Draft method, for development use, may change without warning ***
//  Self test of this class.
GEOUTILS_EXPORT void
    geopip_test (bool verbose);

#endif // GEOUTILS_BUILD_DRAFT_API
//  @end

#ifdef __cplusplus
}
#endif

#endif
